

EVENT_ENTER_GAME = "EVENT_ENTER_GAME"
EVENT_ENTER_ROOM = "EVENT_ENTER_ROOM"
EVENT_ENTER_DESK = "EVENT_ENTER_DESK"
EVENT_DESK_INFO  = "EVENT_DESK_INFO"
EVENT_ROOM_MSG_RECEIVE = "EVENT_ROOM_MSG_RECEIVE"