

EVENT_ENTER_GAME = "EVENT_ENTER_GAME"
EVENT_ENTER_ROOM = "EVENT_ENTER_ROOM"
EVENT_ENTER_DESK = "EVENT_ENTER_DESK"
EVENT_DESK_INFO  = "EVENT_DESK_INFO"
EVENT_ROOM_DETAIL  = "EVENT_ROOM_DETAIL"
EVENT_ROOM_MSG_RECEIVE = "EVENT_ROOM_MSG_RECEIVE"

--未开始
DDZ_STEP_NONE = "none"
--发牌
DDZ_STEP_DEAL = "deal"
--叫地主
DDZ_STEP_LORD = "lord"
--玩游戏
DDZ_STEP_PLAY = "play"
